version: "3"
services: 
  appnode:
    build: 
      context: .
    container_name: appnode
    restart: always
    environment:
      - APP_PORT:3000
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    ports: 
      - 3000:3000
    
  db:
    image: mongo
    ports: 
      - 27017:27017
    restart: always
    volumes: 
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongodb: {}
      
